#ifndef QTBACKGROUNDPROCESS_GLOBAL_H
#define QTBACKGROUNDPROCESS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QT_BUILD_BACKGROUNDPROCESS_LIB)
#	define Q_BACKGROUNDPROCESS_EXPORT Q_DECL_EXPORT
#else
#	define Q_BACKGROUNDPROCESS_EXPORT Q_DECL_IMPORT
#endif

#endif // QBACKGROUNDPROCESS_GLOBAL_H
