#ifndef QBACKGROUNDPROCESS_GLOBAL_H
#define QBACKGROUNDPROCESS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QBACKGROUNDPROCESS_LIBRARY)
#  define QBACKGROUNDPROCESSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QBACKGROUNDPROCESSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QBACKGROUNDPROCESS_GLOBAL_H
