#ifndef QtBACKGROUNDPROCESS_GLOBAL_H
#define QtBACKGROUNDPROCESS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTBACKGROUNDPROCESS_LIBRARY)
#  define QTBACKGROUNDPROCESSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTBACKGROUNDPROCESSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QtBACKGROUNDPROCESS_GLOBAL_H
